package com.oracle.shop.model.javabean;

import java.io.Serializable;

/**
 * 购物车 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Cart implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 购物车标号. */
	private Integer cartid;

	/** 购买数量. */
	private Integer quantity;

	/** 用户编号. */
	private Integer userid;

	/** 商品编号. */
	private Integer goodsid;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public Cart() {
	}

	/**
	 * 购物车标号 傪愝掕偟傑偡.
	 * 
	 * @param cartid
	 *            购物车标号
	 */
	public void setCartid(Integer cartid) {
		this.cartid = cartid;
	}

	/**
	 * 购物车标号 傪庢摼偟傑偡.
	 * 
	 * @return 购物车标号
	 */
	public Integer getCartid() {
		return this.cartid;
	}

	/**
	 * 购买数量 傪愝掕偟傑偡.
	 * 
	 * @param quantity
	 *            购买数量
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * 购买数量 傪庢摼偟傑偡.
	 * 
	 * @return 购买数量
	 */
	public Integer getQuantity() {
		return this.quantity;
	}

	/**
	 * 用户编号 傪愝掕偟傑偡.
	 * 
	 * @param userid
	 *            用户编号
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * 用户编号 傪庢摼偟傑偡.
	 * 
	 * @return 用户编号
	 */
	public Integer getUserid() {
		return this.userid;
	}

	/**
	 * 商品编号 傪愝掕偟傑偡.
	 * 
	 * @param goodsid
	 *            商品编号
	 */
	public void setGoodsid(Integer goodsid) {
		this.goodsid = goodsid;
	}

	/**
	 * 商品编号 傪庢摼偟傑偡.
	 * 
	 * @return 商品编号
	 */
	public Integer getGoodsid() {
		return this.goodsid;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cartid == null) ? 0 : cartid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Cart other = (Cart) obj;
		if (cartid == null) {
			if (other.cartid != null) {
				return false;
			}
		} else if (!cartid.equals(other.cartid)) {
			return false;
		}

		return true;
	}

}
