package com.oracle.shop.model.javabean;

import java.io.Serializable;

/**
 * 收藏夹表 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Likes implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 收藏夹编号. */
	private Integer likesid;

	/** 加入时间. */
	private String likestime;

	/** 分类名称. */
	private String classname;

	/** 用户编号. */
	private Integer userid;

	/** 商品编号. */
	private Integer goodsid;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public Likes() {
	}

	/**
	 * 收藏夹编号 傪愝掕偟傑偡.
	 * 
	 * @param likesid
	 *            收藏夹编号
	 */
	public void setLikesid(Integer likesid) {
		this.likesid = likesid;
	}

	/**
	 * 收藏夹编号 傪庢摼偟傑偡.
	 * 
	 * @return 收藏夹编号
	 */
	public Integer getLikesid() {
		return this.likesid;
	}

	/**
	 * 加入时间 傪愝掕偟傑偡.
	 * 
	 * @param likestime
	 *            加入时间
	 */
	public void setLikestime(String likestime) {
		this.likestime = likestime;
	}

	/**
	 * 加入时间 傪庢摼偟傑偡.
	 * 
	 * @return 加入时间
	 */
	public String getLikestime() {
		return this.likestime;
	}

	/**
	 * 分类名称 傪愝掕偟傑偡.
	 * 
	 * @param classname
	 *            分类名称
	 */
	public void setClassname(String classname) {
		this.classname = classname;
	}

	/**
	 * 分类名称 傪庢摼偟傑偡.
	 * 
	 * @return 分类名称
	 */
	public String getClassname() {
		return this.classname;
	}

	/**
	 * 用户编号 傪愝掕偟傑偡.
	 * 
	 * @param userid
	 *            用户编号
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * 用户编号 傪庢摼偟傑偡.
	 * 
	 * @return 用户编号
	 */
	public Integer getUserid() {
		return this.userid;
	}

	/**
	 * 商品编号 傪愝掕偟傑偡.
	 * 
	 * @param goodsid
	 *            商品编号
	 */
	public void setGoodsid(Integer goodsid) {
		this.goodsid = goodsid;
	}

	/**
	 * 商品编号 傪庢摼偟傑偡.
	 * 
	 * @return 商品编号
	 */
	public Integer getGoodsid() {
		return this.goodsid;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((likesid == null) ? 0 : likesid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Likes other = (Likes) obj;
		if (likesid == null) {
			if (other.likesid != null) {
				return false;
			}
		} else if (!likesid.equals(other.likesid)) {
			return false;
		}

		return true;
	}

}
