
/* Drop Tables */

DROP TABLE CART;
DROP TABLE LIKES;
DROP TABLE ORDER_DETAIL;
DROP TABLE GOODS;
DROP TABLE ORDERS;
DROP TABLE USERS;




/* Create Tables */

CREATE TABLE CART
(
	CART_ID INT NOT NULL AUTO_INCREMENT,
	QUANTITY INT NOT NULL,
	USERID INT NOT NULL,
	GOODID INT NOT NULL,
	PRIMARY KEY (CART_ID)
);


CREATE TABLE GOODS
(
	GOODID INT NOT NULL AUTO_INCREMENT,
	GOODS_NAME VARCHAR(50) NOT NULL,
	BRAND_NAME VARCHAR(30) NOT NULL,
	PRICE DECIMAL(10,2) NOT NULL,
	STOCK INT NOT NULL,
	PICTURE VARCHAR(100) NOT NULL,
	PRIMARY KEY (GOODID)
);


CREATE TABLE LIKES
(
	LIKES_ID INT NOT NULL AUTO_INCREMENT,
	LIKES_TIME VARCHAR(50) NOT NULL,
	CLASS VARCHAR(30) NOT NULL,
	USERID INT NOT NULL,
	GOODID INT NOT NULL,
	PRIMARY KEY (LIKES_ID)
);


CREATE TABLE ORDERS
(
	ORDER_ID INT NOT NULL AUTO_INCREMENT,
	TIME VARCHAR(50) NOT NULL,
	STATUS VARCHAR(10) NOT NULL,
	ADDRESS VARCHAR(50) NOT NULL,
	NOTE TEXT,
	USERID INT NOT NULL,
	PRIMARY KEY (ORDER_ID)
);


CREATE TABLE ORDER_DETAIL
(
	ITEM_ID INT NOT NULL AUTO_INCREMENT,
	ORDER_ID INT NOT NULL,
	GOODID INT NOT NULL,
	PRIMARY KEY (ITEM_ID)
);


CREATE TABLE USERS
(
	USERID INT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	SEX VARCHAR(10) NOT NULL,
	AGE INT,
	PHONE VARCHAR(20) NOT NULL,
	PRIMARY KEY (USERID)
);



/* Create Foreign Keys */

ALTER TABLE CART
	ADD FOREIGN KEY (GOODID)
	REFERENCES GOODS (GOODID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LIKES
	ADD FOREIGN KEY (GOODID)
	REFERENCES GOODS (GOODID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ORDER_DETAIL
	ADD FOREIGN KEY (GOODID)
	REFERENCES GOODS (GOODID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ORDER_DETAIL
	ADD FOREIGN KEY (ORDER_ID)
	REFERENCES ORDERS (ORDER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CART
	ADD FOREIGN KEY (USERID)
	REFERENCES USERS (USERID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LIKES
	ADD FOREIGN KEY (USERID)
	REFERENCES USERS (USERID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ORDERS
	ADD FOREIGN KEY (USERID)
	REFERENCES USERS (USERID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



